### ISSUE TITLE
Error "Things are bad. Refreshing"

### ISSUE THREAD

**Issue by harris910** [justdvl/facebook-auto-liker#3]
Things are bad. refreshing
Traceback (most recent call last):
  File "run.py", line 69, in AutoLiker
    location = likes[i].location
IndexError: list index out of range

Constantly facing this issue when i run your code.

**Comment by david-vendel** [comment]
The code is not maintained and it strongly depends on FB html code. If that
changes (which it does every month or so), the script might have problems
operating correctly.
I am sorry, I won't have time to maintain this code.

**Comment by harris910** [comment]
Hey, can you guide where to look for changes in your code as i am novice to
this language.
